services:

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  django:
    build: .
    container_name: django_tasks_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tasks:/app
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=tasks.settings
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - redis